packages:
  - apps/*
  - packages/*
  - plugins/*
  - mcp/*
  - '!apps/services-hono'
catalogs:
  # 框架
  framework:
    'react': '18.3.1'
    'react-dom': '18.3.1'
    'react-router': '7.9.4'
  # 构建
  build:
    'vite': '7.2.0'
    'turbo': '^2.5.8'
    'tsdown': '^0.14.1'
    'rimraf': '^6.0.1'
    '@vitejs/plugin-legacy': '7.2.1'
    '@module-federation/enhanced': '0.20.0'
    '@module-federation/vite': '1.8.1'
  # 方法
  util:
    'ahooks': '3.9.5'
    'lodash-es': '4.17.21'
    'axios': '1.12.2'
    'qs': '6.14.0'
    '@dnd-kit/core': '6.3.1'
    '@dnd-kit/modifiers': '9.0.0'
    '@dnd-kit/sortable': '10.0.0'
    '@dnd-kit/utilities': '3.2.2'
    '@uiw/react-codemirror': '4.25.2'
    'classnames': '2.5.1'
    'clipboard': '2.0.11'
    'codemirror': '5.65.18'
    'dayjs': '1.11.18'
    'immer': '10.1.3'
    'insert-css': '2.0.0'
    'js-beautify': '1.15.4'
    'js-cookie': '3.0.5'
    'react-cookie': '8.0.1'
    'react-draggable': '4.5.0'
    'react-infinite-scroll-component': '6.1.0'
    'react-resizable': '3.0.5'
    'react-sticky-box': '2.0.5'
    'use-immer': '0.11.0'
    'uuid': '13.0.0'
    'zustand': '5.0.8'
    'react-intl': '7.1.13'
    'tencentcloud-sdk-nodejs-tmt': '4.1.117'
    'zod': '^3.23.8'
    'zod-to-json-schema': '3.24.6'
    'node-fetch': '3.3.2'
  # 开发
  dev:
    '@vitejs/plugin-react': '^5.0.4'
    'dotenv': '17.2.3'
    'picocolors': '1.1.1'
    'shx': '^0.4.0'
  # 组件
  ui:
    'antd': '5.27.4'
    '@ant-design/v5-patch-for-react-19': '^1.0.3'
    'sass': '1.93.2'
    '@ant-design/icons': '6.1.0'
    '@carbon/icons-react': '11.69.0'
    '@antv/x6': '2.18.1'
    '@antv/x6-react-shape': '2.2.3'
    'rc-virtual-list': '3.19.2'
  # 规范
  lint:
    '@eslint/js': '^9.37.0'
    'eslint': '^9.37.0'
    'eslint-plugin-react-hooks': '^7.0.0'
    'eslint-plugin-react-refresh': '^0.4.23'
    'globals': '^16.4.0'
    'typescript': '~5.9.3'
    'typescript-eslint': '^8.46.1'
    'prettier': '^3.6.2'
    'eslint-config-prettier': '^10.1.8'
    'eslint-plugin-prettier': '^5.5.4'
    'stylelint': '16.25.0'
    'stylelint-config-prettier': '^9.0.5'
    'stylelint-config-standard': '^39.0.1'
    'stylelint-config-standard-scss': '^16.0.0'
    'stylelint-prettier': '^5.0.3'
    'stylelint-scss': '^6.12.1'
    '@commitlint/cli': '^20.1.0'
    '@commitlint/config-conventional': '^20.0.0'
    '@commitlint/prompt-cli': '^20.1.0'
    'husky': '9.1.7'
    'lint-staged': '16.2.4'
  # 类型
  type:
    '@types/node': '^24.7.2'
    '@types/react': '^18.3.17'
    '@types/react-dom': '^18.3.5'
    '@types/insert-css': '^2.0.3'
    '@types/codemirror': '^5.60.16'
    '@types/js-beautify': '^1.14.3'
    '@types/js-cookie': '^3.0.6'
    '@types/lodash-es': '^4.17.12'
    '@types/qs': '^6.14.0'
    '@types/react-resizable': '^3.0.8'
    '@types/express': '^5.0.3'
    '@types/dockerode': '^3.3.44'
    '@types/cors': '^2.8.19'
    '@types/node-fetch': '^2.6.13'
  ai:
    '@copilotkit/react-core': '1.10.6'
    '@copilotkit/react-ui': '1.10.6'
    '@copilotkit/runtime': '1.10.6'
    'openai': '^4.68.1'
    '@langchain/anthropic': '0.3.33'
    '@langchain/ollama': '1.0.0'
    '@langchain/openai': '1.0.0'
    '@modelcontextprotocol/sdk': '^1.21.0'
  # 服务端
  server:
    'dockerode': '^4.0.9'
    'cors': '^2.8.5'
    'express': '^5.1.0'
