// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.0--rc3
// source: TopicMessage.proto

package msg_consumer

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopicMessageList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*TopicMessage        `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicMessageList) Reset() {
	*x = TopicMessageList{}
	mi := &file_TopicMessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicMessageList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicMessageList) ProtoMessage() {}

func (x *TopicMessageList) ProtoReflect() protoreflect.Message {
	mi := &file_TopicMessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicMessageList.ProtoReflect.Descriptor instead.
func (*TopicMessageList) Descriptor() ([]byte, []int) {
	return file_TopicMessage_proto_rawDescGZIP(), []int{0}
}

func (x *TopicMessageList) GetMessages() []*TopicMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type TopicMessage struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Id            int64                     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DataSrcId     int32                     `protobuf:"varint,2,opt,name=dataSrcId,proto3" json:"dataSrcId,omitempty"`
	Data          []*TopicMessage_DataArray `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicMessage) Reset() {
	*x = TopicMessage{}
	mi := &file_TopicMessage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicMessage) ProtoMessage() {}

func (x *TopicMessage) ProtoReflect() protoreflect.Message {
	mi := &file_TopicMessage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicMessage.ProtoReflect.Descriptor instead.
func (*TopicMessage) Descriptor() ([]byte, []int) {
	return file_TopicMessage_proto_rawDescGZIP(), []int{1}
}

func (x *TopicMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TopicMessage) GetDataSrcId() int32 {
	if x != nil {
		return x.DataSrcId
	}
	return 0
}

func (x *TopicMessage) GetData() []*TopicMessage_DataArray {
	if x != nil {
		return x.Data
	}
	return nil
}

type TopicMessage_DataArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         map[string]string      `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicMessage_DataArray) Reset() {
	*x = TopicMessage_DataArray{}
	mi := &file_TopicMessage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicMessage_DataArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicMessage_DataArray) ProtoMessage() {}

func (x *TopicMessage_DataArray) ProtoReflect() protoreflect.Message {
	mi := &file_TopicMessage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicMessage_DataArray.ProtoReflect.Descriptor instead.
func (*TopicMessage_DataArray) Descriptor() ([]byte, []int) {
	return file_TopicMessage_proto_rawDescGZIP(), []int{1, 0}
}

func (x *TopicMessage_DataArray) GetValue() map[string]string {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_TopicMessage_proto protoreflect.FileDescriptor

const file_TopicMessage_proto_rawDesc = "" +
	"\n" +
	"\x12TopicMessage.proto\"=\n" +
	"\x10TopicMessageList\x12)\n" +
	"\bmessages\x18\x01 \x03(\v2\r.TopicMessageR\bmessages\"\xea\x01\n" +
	"\fTopicMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\tdataSrcId\x18\x02 \x01(\x05R\tdataSrcId\x12+\n" +
	"\x04data\x18\x03 \x03(\v2\x17.TopicMessage.DataArrayR\x04data\x1a\x7f\n" +
	"\tDataArray\x128\n" +
	"\x05value\x18\x01 \x03(\v2\".TopicMessage.DataArray.ValueEntryR\x05value\x1a8\n" +
	"\n" +
	"ValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_TopicMessage_proto_rawDescOnce sync.Once
	file_TopicMessage_proto_rawDescData []byte
)

func file_TopicMessage_proto_rawDescGZIP() []byte {
	file_TopicMessage_proto_rawDescOnce.Do(func() {
		file_TopicMessage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TopicMessage_proto_rawDesc), len(file_TopicMessage_proto_rawDesc)))
	})
	return file_TopicMessage_proto_rawDescData
}

var file_TopicMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_TopicMessage_proto_goTypes = []any{
	(*TopicMessageList)(nil),       // 0: TopicMessageList
	(*TopicMessage)(nil),           // 1: TopicMessage
	(*TopicMessage_DataArray)(nil), // 2: TopicMessage.DataArray
	nil,                            // 3: TopicMessage.DataArray.ValueEntry
}
var file_TopicMessage_proto_depIdxs = []int32{
	1, // 0: TopicMessageList.messages:type_name -> TopicMessage
	2, // 1: TopicMessage.data:type_name -> TopicMessage.DataArray
	3, // 2: TopicMessage.DataArray.value:type_name -> TopicMessage.DataArray.ValueEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_TopicMessage_proto_init() }
func file_TopicMessage_proto_init() {
	if File_TopicMessage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TopicMessage_proto_rawDesc), len(file_TopicMessage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TopicMessage_proto_goTypes,
		DependencyIndexes: file_TopicMessage_proto_depIdxs,
		MessageInfos:      file_TopicMessage_proto_msgTypes,
	}.Build()
	File_TopicMessage_proto = out.File
	file_TopicMessage_proto_goTypes = nil
	file_TopicMessage_proto_depIdxs = nil
}
